version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:11.12.0

    steps:
      - checkout
      - run: yarn
      - run: CI=true yarn test ./src
      - codecov/upload:
          file: {{ coverage_report_filepath }}
